package pckElevator_V1;

import javax.swing.JTextArea;

public class jFrameMainView extends javax.swing.JFrame {
    //data
    private ControllerDemo controller;
    
    //pass in the reference into jframe
    public jFrameMainView(ControllerDemo controller) {
        this.controller = controller;
        initComponents();
        this.setTitle("MVC Demo View");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanellMainView = new javax.swing.JPanel();
        btnMoveElevator = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDisplayElevators = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMoveElevator.setText("Move Elevator");
        btnMoveElevator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveElevatorActionPerformed(evt);
            }
        });

        areaDisplayElevators.setColumns(20);
        areaDisplayElevators.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        areaDisplayElevators.setRows(5);
        jScrollPane1.setViewportView(areaDisplayElevators);

        javax.swing.GroupLayout jPanellMainViewLayout = new javax.swing.GroupLayout(jPanellMainView);
        jPanellMainView.setLayout(jPanellMainViewLayout);
        jPanellMainViewLayout.setHorizontalGroup(
            jPanellMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellMainViewLayout.createSequentialGroup()
                .addGroup(jPanellMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellMainViewLayout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(btnMoveElevator, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanellMainViewLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanellMainViewLayout.setVerticalGroup(
            jPanellMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellMainViewLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnMoveElevator, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanellMainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanellMainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoveElevatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveElevatorActionPerformed
        controller.startAnimation();
        
    }//GEN-LAST:event_btnMoveElevatorActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // create the controller object and 
        // Execute initialization of all requied business objects
        ControllerDemo controller = new ControllerDemo();
        /* Create and display the form */
        controller.initUseCase();
        
        /* create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                // create the window
                // Let controller know the window 
                // Visualize the window, pass in the 'controller'
                jFrameMainView mainWindow = new jFrameMainView( controller );
                controller.setWindow ( mainWindow );
                controller.displayElevators();      //initialize withe something on the screen
                mainWindow.setVisible(true);
            }//void run()
        });// java.awt.EventQueue
    }// main()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDisplayElevators;
    private javax.swing.JButton btnMoveElevator;
    private javax.swing.JPanel jPanellMainView;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    //getters and Setter
    public JTextArea getAreaDisplayElevators() {
        return areaDisplayElevators;
    }
}
